// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'PART 0: INTRODUCTION TO PHYSICAL AI AND HUMANOID ROBOTICS',
      link: {
        type: 'doc',
        id: 'part0-introduction/part0-introduction'
      },
      items: [
        'part0-introduction/chapter-1-why-physical-ai-is-the-next-frontier',
        'part0-introduction/chapter-2-the-new-workflow-spec-driven-physical-ai'
      ]
    },
    {
      type: 'category',
      label: 'PART 1: THE ROBOTIC NERVOUS SYSTEM (ROS 2)',
      link: {
        type: 'doc',
        id: 'part1-module1/part1-introduction'
      },
      items: [
        'part1-module1/chapter-3-ros-2-crash-course',
        'part1-module1/chapter-4-talking-to-robots',
        'part1-module1/chapter-5-building-real-packages',
        'part1-module1/chapter-6-bridging-ai-agents-to-ros',
        'part1-module1/part-1-self-assessment'
      ]
    }
  ],

};

export default sidebars;
